name: Bot-CPAN
version: 0.83
abstract: provides CPAN services via IRC
author: Adam J. Foxson <afoxson@pobox.com>
license: perl
distribution_type: module
requires:
  Attribute::Handlers: 0.78
  CPANPLUS: 0.042
  HTTP::Request: 1.30
  LWP::UserAgent: 2.003
  Mail::Internet: 1.58
  Math::Round: 0.05
  Net::NNTP: 2.22
  POE: 0.26
  POE::Component::IRC: 2.9
  Statistics::Descriptive: 2.6
  URI: 1.24
  XML::Parser: 2.33
  XML::RSS::Parser: 0.21
recommends:
  Encode: 1.97
private:
  directory:
    - inc
generated_by: Module::Install version 0.23
