abstract: provides CPAN services via IRC
author: 'Adam J. Foxson <afoxson@pobox.com>'
distribution_type: module
generated_by: Module::Install version 0.63
license: gpl
name: Bot-CPAN
no_index:
  directory:
    - inc
    - t
recommends:
  Config::Auto: 0.16
  Encode: 2.18
  Getopt::Long: 2.35
requires:
  Attribute::Handlers: 0.78
  CPAN::DistnameInfo: 0.06
  Class::Phrasebook: 0.88
  Compress::Zlib: 1.41
  Error: 0.16
  File::Listing: 1.15
  HTTP::Request: 1.40
  LWP::UserAgent: 2.033
  Mail::Internet: 1.74
  Math::Round: 0.05
  Net::NNTP: 2.23
  POE: 0.3502
  POE::Component::IRC: 4.93
  Sort::Versions: 1.5
  Statistics::Descriptive: 2.6
  Storable: 2.15
  Text::Wrap: 2005.082401
  URI: 1.35
  XML::Parser: 2.34
  XML::RSS::Parser: 4
version: 1.11
