name: Bot-CPAN
version: 1.7
abstract: provides CPAN services via IRC
author: Adam J. Foxson <afoxson@pobox.com>
license: gpl
distribution_type: module
requires:
  Attribute::Handlers: 0.78
  Class::Phrasebook: 0.88
  CPANPLUS: 0.042
  HTTP::Request: 1.30
  LWP::UserAgent: 2.003
  Mail::Internet: 1.58
  Math::Round: 0.05
  Net::NNTP: 2.22
  POE: 0.26
  POE::Component::IRC: 2.9
  Statistics::Descriptive: 2.6
  URI: 1.24
  XML::Parser: 2.33
  XML::RSS::Parser: 0.21
recommends:
  Encode: 1.97
  Config::Auto: 0.03
  Getopt::Long: 2.23
  Module::CPANTS: 0.20030725
private:
  directory:
    - inc
generated_by: Module::Install version 0.23
